version: '3.3'

services:

  gost-db:
    image: "geodan/gost-db"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./dumps:/monica/dumps"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=gost
    networks:
      reseau:
        ipv4_address: 192.168.0.3

  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - 5555:80
    depends_on:
      - gost-db
    environment:
      - PGADMIN_DEFAULT_EMAIL=seb
      - PGADMIN_DEFAULT_PASSWORD=seb
    networks:
      reseau:
        ipv4_address: 192.168.0.4
      
  notebook:
    image: "monicaproject/notebook"
    ports:
      - 8888:8888
    depends_on:
      - gost-db
      - pgadmin
      
    volumes: 
      - ./notebooks:/home/jovyan
  
    networks:
        reseau:
          ipv4_address: 192.168.0.5


volumes:
  pgdata:
  
networks:
  reseau:
    external: true